version: '3.1'

services:

  db:
    image: mariadb
    container_name: fin-db-container
    command: --max_allowed_packet=67108864
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: davide
      MARIADB_DATABASE: musiclibrary
    ports:
      - "3306:3306"
